### ISSUE TITLE
Use bit field instead of bitwise operations

### ISSUE THREAD

**Issue by pathawks** [rdanbrook/cirugia#1]
How do you feel about turning `romheader` into a bit field instead of using all the bitwise operations? This would make the code easier to read, and give the compiler a bit more freedom in optimizing the bitwise arithmetic.

[Instead of](https://github.com/rdanbrook/cirugia/blob/b4685037beab80bd563fce652bc0f3464e8df12b/core/header.c#L261-L265)

``` c
return romheader[6] & 0x04 ? 1 : 0;
```

this would allow us to instead write

``` c
return romheader.trainer;
```

I wouldn't mind working on a PR if this is something you are open to, but I wanted to check first as this would impact a _lot_ of code.

**Comment by rdanbrook** [comment]
Thanks for taking interest in this project.

The only concern I have with this really, is that it might cause headaches dealing with different versions of the header (iNES vs NES 2.0). I don't really find it hard to read, of course I wrote it so it came from my twisted brain in the first place.

One day (maybe soon when I take a vacation) I'll add tile import/export, and there will be a lot of restructuring done. I may restructure some of this header code as well at that time.

**Comment by pathawks** [comment]
> The only concern I have with this really, is that it might cause headaches dealing with different versions of the header (iNES vs NES 2.0).

I think it is ok because almost everything new in NES 2.0 should just be zeroed out in iNES.

Here is some rough sketching of what I had in mind, just for posterity. `union` this with `romheader` and Rock & Roll.

``` c
struct {
    unsigned int magic_number : 32; // Bytes 0-3
    unsigned int prom_size_low : 8; // Byte 4
    unsigned int crom_size_low : 8; // Byte 5
    unsigned int mirroring : 1;     // Byte 6
    unsigned int battery : 1;
    unsigned int trainer : 1;
    unsigned int four_screen_mode : 1;
    unsigned int map_low : 4;
    unsigned int sys : 2;           // Byte 7
    unsigned int version : 2;
    unsigned int map_mid : 4;
    unsigned int submapper : 4;     // Byte 8
    unsigned int map_high: 4;
    unsigned int crom_size_high : 4;// Byte 9
    unsigned int prom_size_high : 4;
    unsigned int pram_battery : 4;  // Byte 10
    unsigned int pram_no_battery : 4;
    unsigned int cram_battery : 4;  // Byte 11
    unsigned int cram_no_battery : 4;
    unsigned int tvsystem : 2;      // Byte 12
    unsigned int : 6;
    unsigned int vsmode : 4;        // Byte 13
    unsigned int vsppu : 4;
    unsigned int reserved : 16;     // Bytes 14-15
};
```

Closing this for now, but let me know if there is something I can do to help in the future :+1:
